//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChamCong_v05.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChamCong_v05.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi.
        /// </summary>
        public static string Caption_Loi {
            get {
                return ResourceManager.GetString("Caption_Loi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        public static string Caption_ThongBao {
            get {
                return ResourceManager.GetString("Caption_ThongBao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận.
        /// </summary>
        public static string Caption_XacNhan {
            get {
                return ResourceManager.GetString("Caption_XacNhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CNS {
            get {
                object obj = ResourceManager.GetObject("CNS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KR.
        /// </summary>
        public static string SymKhongRa {
            get {
                return ResourceManager.GetString("SymKhongRa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KV.
        /// </summary>
        public static string SymKhongVao {
            get {
                return ResourceManager.GetString("SymKhongVao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c3.
        /// </summary>
        public static string SymPhuCapDem {
            get {
                return ResourceManager.GetString("SymPhuCapDem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x3.
        /// </summary>
        public static string SymPhuCapNgayLe {
            get {
                return ResourceManager.GetString("SymPhuCapNgayLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x2.
        /// </summary>
        public static string SymPhuCapNgayNghi {
            get {
                return ResourceManager.GetString("SymPhuCapNgayNghi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TC.
        /// </summary>
        public static string SymPhuCapTangCuong {
            get {
                return ResourceManager.GetString("SymPhuCapTangCuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T3.
        /// </summary>
        public static string SymPhuCapTangCuongDem {
            get {
                return ResourceManager.GetString("SymPhuCapTangCuongDem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xK.
        /// </summary>
        public static string SymPhuCapTuyChinhNgayDem {
            get {
                return ResourceManager.GetString("SymPhuCapTuyChinhNgayDem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xK.
        /// </summary>
        public static string SymPhuCapTuyChinhTatCa {
            get {
                return ResourceManager.GetString("SymPhuCapTuyChinhTatCa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -S.
        /// </summary>
        public static string SymSomBiTru {
            get {
                return ResourceManager.GetString("SymSomBiTru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BS.
        /// </summary>
        public static string SymSomPhaiLamBu {
            get {
                return ResourceManager.GetString("SymSomPhaiLamBu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -T.
        /// </summary>
        public static string SymTreBiTru {
            get {
                return ResourceManager.GetString("SymTreBiTru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BT.
        /// </summary>
        public static string SymTrePhaiLamBu {
            get {
                return ResourceManager.GetString("SymTrePhaiLamBu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản hoặc mật khẩu chưa đúng. Vui lòng điền lại..
        /// </summary>
        public static string Text_Acc_Pass_incorrect {
            get {
                return ResourceManager.GetString("Text_Acc_Pass_incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa được cấp quyền ghi file vào folder..
        /// </summary>
        public static string Text_AccessDenied {
            get {
                return ResourceManager.GetString("Text_AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian tối thiểu để xác nhận làm thêm không hợp lệ.
        /// </summary>
        public static string Text_AfterOTKoHL {
            get {
                return ResourceManager.GetString("Text_AfterOTKoHL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn huỷ xác nhận tính phụ cấp tăng cường 50%?.
        /// </summary>
        public static string Text_CancelXacNhan_PCTC50 {
            get {
                return ResourceManager.GetString("Text_CancelXacNhan_PCTC50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa được phân quyền thao tác..
        /// </summary>
        public static string Text_ChuaCapQuyenPhongBanThaoTac {
            get {
                return ResourceManager.GetString("Text_ChuaCapQuyenPhongBanThaoTac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa chọn Nhân viên..
        /// </summary>
        public static string Text_ChuaChonNV {
            get {
                return ResourceManager.GetString("Text_ChuaChonNV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa chọn {0}..
        /// </summary>
        public static string Text_ChuaChonXXX {
            get {
                return ResourceManager.GetString("Text_ChuaChonXXX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa lựa chọn ca nào..
        /// </summary>
        public static string Text_ChuaLuaChonCa {
            get {
                return ResourceManager.GetString("Text_ChuaLuaChonCa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi trong quá trình thực hiện. Vui lòng thử lại..
        /// </summary>
        public static string Text_CoLoi {
            get {
                return ResourceManager.GetString("Text_CoLoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng kiểm tra kỹ thời gian vào ra các nhân viên trước khi xác nhận để không làm sai lệch công của nhân viên. 
        ///Đồng ý xác nhận các giờ đã chọn?.
        /// </summary>
        public static string Text_ConfirmDongY_XacNhan {
            get {
                return ResourceManager.GetString("Text_ConfirmDongY_XacNhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn kết công THÁNG {0} cho các bộ phận?
        ///Bấm Yes để kết công cho bộ phận và đợi đến lúc có thông báo kết quả.
        ///Bấm No để quay trở lại..
        /// </summary>
        public static string Text_ConfirmKetCongBoPhan {
            get {
                return ResourceManager.GetString("Text_ConfirmKetCongBoPhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn lưu nhiệm vụ này?.
        /// </summary>
        public static string Text_ConfirmLuuNhiemVu {
            get {
                return ResourceManager.GetString("Text_ConfirmLuuNhiemVu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nếu xoá nhiệm vụ này thì các nhân viên được giao nhiệm vụ trước đây sẽ không đảm nhận nhiệm vụ này nữa.
        ///Bạn muốn Xoá nhiệm vụ?.
        /// </summary>
        public static string Text_ConfirmXoaNhiemVu {
            get {
                return ResourceManager.GetString("Text_ConfirmXoaNhiemVu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian cho phép ra sớm không hợp lệ.
        /// </summary>
        public static string Text_CPSOMKoHL {
            get {
                return ResourceManager.GetString("Text_CPSOMKoHL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian cho phép vào trễ không hợp lệ.
        /// </summary>
        public static string Text_CPTREKoHL {
            get {
                return ResourceManager.GetString("Text_CPTREKoHL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giờ kết thúc nhận diện vào không hợp lệ.
        /// </summary>
        public static string Text_CutInnKoHL {
            get {
                return ResourceManager.GetString("Text_CutInnKoHL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giờ kết thúc nhận diện ra không hợp lệ.
        /// </summary>
        public static string Text_CutOutKoHL {
            get {
                return ResourceManager.GetString("Text_CutOutKoHL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã thực hiện xong..
        /// </summary>
        public static string Text_DaThucHienXong {
            get {
                return ResourceManager.GetString("Text_DaThucHienXong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máy chấm công CHƯA LẤY ĐƯỢC DỮ LIỆU MỚI NHẤT do mất kết nối với máy chủ. Vui lòng hạn chế chỉnh sửa giờ chấm công..
        /// </summary>
        public static string Text_DuLieuChamCongChuaUpdate {
            get {
                return ResourceManager.GetString("Text_DuLieuChamCongChuaUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File đang mở bởi ứng dụng khác..
        /// </summary>
        public static string Text_FileDangMoBoiUngDungKhac {
            get {
                return ResourceManager.GetString("Text_FileDangMoBoiUngDungKhac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy folder lưu trữ..
        /// </summary>
        public static string Text_FolderNotFound {
            get {
                return ResourceManager.GetString("Text_FolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giờ chấm công này đã được xác nhận, không thể thay đổi..
        /// </summary>
        public static string Text_GioDaXacnhanKhongTheThayDoi {
            get {
                return ResourceManager.GetString("Text_GioDaXacnhanKhongTheThayDoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giờ làm thêm vượt ngưỡng thời gian ở lại..
        /// </summary>
        public static string Text_GioLamThemLonHonTGOLai {
            get {
                return ResourceManager.GetString("Text_GioLamThemLonHonTGOLai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giờ ra không hợp lệ.
        /// </summary>
        public static string Text_GioRaaKoHL {
            get {
                return ResourceManager.GetString("Text_GioRaaKoHL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giờ vào không hợp lệ.
        /// </summary>
        public static string Text_GioVaoKoHL {
            get {
                return ResourceManager.GetString("Text_GioVaoKoHL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các hệ số lương, BHXH cộng thêm chưa hợp lệ..
        /// </summary>
        public static string Text_HeSoLCB_CV_BHXH_ChuaHopLe {
            get {
                return ResourceManager.GetString("Text_HeSoLCB_CV_BHXH_ChuaHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết nối CSDL không thành công. Bấm Retry để thử lại. Bấm Cancel để thoát ứng dụng..
        /// </summary>
        public static string Text_KetNoiCSDLKoThanhCong {
            get {
                return ResourceManager.GetString("Text_KetNoiCSDLKoThanhCong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khoảng thời gian {0} CÓ NGÀY ĐÃ KẾT LƯƠNG THÁNG nên không thể {1}. 
        ///Vui lòng chọn lại các ngày {2} chưa kết lương tháng..
        /// </summary>
        public static string Text_KhoangTGDaKetCong_KoChinhSuaGioCC {
            get {
                return ResourceManager.GetString("Text_KhoangTGDaKetCong_KoChinhSuaGioCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khoảng thời gian xem công quá dài, dữ liệu chấm công từ server lớn làm chậm ứng dụng, có thể xảy ra lỗi không đủ bộ nhớ RAM. 
        ///Bạn muốn tiếp tục?.
        /// </summary>
        public static string Text_KhoangThoiGianXemCongQuaDai {
            get {
                return ResourceManager.GetString("Text_KhoangThoiGianXemCongQuaDai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể ghi được file báo biểu..
        /// </summary>
        public static string Text_KhongTheGhiFile {
            get {
                return ResourceManager.GetString("Text_KhongTheGhiFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xác nhận ca làm việc này cho nhân viên.
        ///Vui lòng chọn ca phù hợp hoặc liên hệ bộ phận kỹ thuật để được trợ giúp..
        /// </summary>
        public static string Text_KhongTheXacNhanCaTach_KoDuDieuKienTach {
            get {
                return ResourceManager.GetString("Text_KhongTheXacNhanCaTach_KoDuDieuKienTach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa được phân quyền thực hiện chức năng này..
        /// </summary>
        public static string Text_KoCoQuyen {
            get {
                return ResourceManager.GetString("Text_KoCoQuyen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có quyền ghi chuỗi kết nối vào Folder. Vui lòng thử lại..
        /// </summary>
        public static string Text_KoCoQuyenGhiChuoiKetNoiCSDL {
            get {
                return ResourceManager.GetString("Text_KoCoQuyenGhiChuoiKetNoiCSDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa được cấp quyền ghi file vào folder..
        /// </summary>
        public static string Text_KoCoQuyenGhiFile {
            get {
                return ResourceManager.GetString("Text_KoCoQuyenGhiFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có quyền truy cập file {0}..
        /// </summary>
        public static string Text_KoCoQuyenTruyCapFileX {
            get {
                return ResourceManager.GetString("Text_KoCoQuyenTruyCapFileX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể thực hiện ghi chuỗi kết nối vào Folder lưu trữ. Vui lòng thử lại..
        /// </summary>
        public static string Text_KoGhiDuocChuoiKetNoiCSDL {
            get {
                return ResourceManager.GetString("Text_KoGhiDuocChuoiKetNoiCSDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể kết nối CSDL. 
        ///Lỗi:
        ///.
        /// </summary>
        public static string Text_KoTheKetNoiCSDL {
            get {
                return ResourceManager.GetString("Text_KoTheKetNoiCSDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể sửa hay xoá giờ đã qua xác nhận..
        /// </summary>
        public static string Text_KoTheSuaXoaGioDaXN {
            get {
                return ResourceManager.GetString("Text_KoTheSuaXoaGioDaXN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể thực hiện xác nhận này! Vui lòng liên hệ bộ phận kỹ thuật để được trợ giúp..
        /// </summary>
        public static string Text_KoTheThucHienXN {
            get {
                return ResourceManager.GetString("Text_KoTheThucHienXN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy file {0}..
        /// </summary>
        public static string Text_KoTimThayFileX {
            get {
                return ResourceManager.GetString("Text_KoTimThayFileX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy folder lưu trữ {0}..
        /// </summary>
        public static string Text_KoTimThayFolderX {
            get {
                return ResourceManager.GetString("Text_KoTimThayFolderX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đọc file dữ liệu từ excel thất bại.
        ///Vui lòng thử lại hoặc liên hệ bộ phận kỹ thuật để được trợ giúp..
        /// </summary>
        public static string Text_LoiDocFileExcel {
            get {
                return ResourceManager.GetString("Text_LoiDocFileExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xảy ra lỗi trong quá trình thực hiện. Vui lòng thử lại..
        /// </summary>
        public static string Text_LoiTrongQuaTrinhThucHien {
            get {
                return ResourceManager.GetString("Text_LoiTrongQuaTrinhThucHien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mất kết nối với CSDL. Vui lòng thử lại sau..
        /// </summary>
        public static string Text_MatKetNoiCSDL {
            get {
                return ResourceManager.GetString("Text_MatKetNoiCSDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn nhập thời gian làm thêm chưa hợp lệ. 
        ///Vui lòng nhập lại đúng định dạng thời gian &quot;hh:mm&quot;..
        /// </summary>
        public static string Text_NhapThoiGianLamThemChuaHopLe {
            get {
                return ResourceManager.GetString("Text_NhapThoiGianLamThemChuaHopLe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giờ kết thúc nghỉ trưa không hợp lệ.
        /// </summary>
        public static string Text_OffLunKoHL {
            get {
                return ResourceManager.GetString("Text_OffLunKoHL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giờ bắt đầu nhận diện vào không hợp lệ.
        /// </summary>
        public static string Text_OnnInnKoHL {
            get {
                return ResourceManager.GetString("Text_OnnInnKoHL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giờ bắt đầu nghỉ trưa không hợp lệ.
        /// </summary>
        public static string Text_OnnLunKoHL {
            get {
                return ResourceManager.GetString("Text_OnnLunKoHL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giờ bắt đầu nhận diện ra không hợp lệ.
        /// </summary>
        public static string Text_OnnOutKoHL {
            get {
                return ResourceManager.GetString("Text_OnnOutKoHL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không hỗ trợ định dạng file hoặc đường dẫn file {0} quá dài..
        /// </summary>
        public static string Text_UnsupportedFile_PathTooLong {
            get {
                return ResourceManager.GetString("Text_UnsupportedFile_PathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng thử lại..
        /// </summary>
        public static string Text_Vuilongthulai {
            get {
                return ResourceManager.GetString("Text_Vuilongthulai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công nhập không hợp lệ.
        /// </summary>
        public static string Text_WKDayKoHL {
            get {
                return ResourceManager.GetString("Text_WKDayKoHL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn chuyển đổi giờ {0} {1} thành giờ {2} {3} cho {4}?.
        /// </summary>
        public static string Text_xacNhanChuyenDoiGioDonGian {
            get {
                return ResourceManager.GetString("Text_xacNhanChuyenDoiGioDonGian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các nhân viên đã xin phép vắng trong tháng các ngày như bên dưới.
        ///Bạn muốn khai báo thêm các ngày bạn vừa chọn?
        ///Bấm Yes để tiếp tục. Bấm No để quay trở lại.
        ///{0}.
        /// </summary>
        public static string Text_XacNhanKhaiBaoThemCacNgayVang {
            get {
                return ResourceManager.GetString("Text_XacNhanKhaiBaoThemCacNgayVang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn lưu thông tin nhân viên?.
        /// </summary>
        public static string Text_XacNhanLuuThongTinNV {
            get {
                return ResourceManager.GetString("Text_XacNhanLuuThongTinNV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa giờ {0} {1} sang {2}?.
        /// </summary>
        public static string Text_xacNhanSuaGioDonGian_dungmucdich {
            get {
                return ResourceManager.GetString("Text_xacNhanSuaGioDonGian_dungmucdich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn sửa giờ {0} {1} sang {2} cho {3}?
        ///Vui lòng xem kỹ NGÀY, GIỜ đã nhập! 
        ///CHÚ Ý: trường hợp LÀM QUA ĐÊM thì giờ ra sau giờ vào 1 ngày.
        ///Bấm Yes để tiếp tục. Bấm No để trở về..
        /// </summary>
        public static string Text_xacNhanSuaGioDonGian_saimucdich {
            get {
                return ResourceManager.GetString("Text_xacNhanSuaGioDonGian_saimucdich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn vui lòng xem kỹ lại giờ {0} trước khi sửa giờ để không làm sai lệch giờ chấm công của nhân viên.
        ///Tiếp tục sửa giờ {0} {1} hàng loạt cho các nhân viên?.
        /// </summary>
        public static string Text_xacNhanSuaGioHangLoat {
            get {
                return ResourceManager.GetString("Text_xacNhanSuaGioHangLoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn sửa giờ ra {0} cho nhân viên {1}?
        ///Vui lòng xem kỹ ngày nếu là giờ qua đêm của ngày hôm sau..
        /// </summary>
        public static string Text_xacNhanSuaGioRaaDonGian {
            get {
                return ResourceManager.GetString("Text_xacNhanSuaGioRaaDonGian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn sửa giờ vào {0} cho nhân viên {1}?
        ///Vui lòng xem kỹ ngày nếu là giờ qua đêm của ngày hôm trước..
        /// </summary>
        public static string Text_xacNhanSuaGioVaoDonGian {
            get {
                return ResourceManager.GetString("Text_xacNhanSuaGioVaoDonGian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn thêm các giờ chấm công tay cho các nhân viên?
        ///Vui lòng kiểm tra kỹ thời gian nhập để không làm sai lệch công của nhân viên..
        /// </summary>
        public static string Text_XacNhanThemChamCongTayChoQL {
            get {
                return ResourceManager.GetString("Text_XacNhanThemChamCongTayChoQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm giờ {0} {1} cho {2}?.
        /// </summary>
        public static string Text_xacNhanThemGioDonGian_dungmucdich {
            get {
                return ResourceManager.GetString("Text_xacNhanThemGioDonGian_dungmucdich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn thêm giờ {0} {1} cho {2}?
        ///Vui lòng xem kỹ NGÀY, GIỜ đã nhập! 
        ///CHÚ Ý: trường hợp LÀM QUA ĐÊM thì giờ ra sau giờ vào 1 ngày.
        ///Bấm Yes để tiếp tục. Bấm No để trở về..
        /// </summary>
        public static string Text_xacNhanThemGioDonGian_saimucdic {
            get {
                return ResourceManager.GetString("Text_xacNhanThemGioDonGian_saimucdic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn vui lòng xem kỹ lại thời gian nhân viên thiếu giờ vào, giờ ra trước khi thêm giờ để không làm sai lệch giờ chấm công của nhân viên.
        ///Tiếp tục thêm giờ {0} {1} hàng loạt cho các nhân viên?.
        /// </summary>
        public static string Text_xacNhanThemGioHangLoat {
            get {
                return ResourceManager.GetString("Text_xacNhanThemGioHangLoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn thêm giờ ra {0} cho nhân viên {1}?
        ///Vui lòng xem kỹ ngày nếu là ca qua đêm của ngày hôm sau..
        /// </summary>
        public static string Text_xacNhanThemGioRaaDonGian {
            get {
                return ResourceManager.GetString("Text_xacNhanThemGioRaaDonGian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn thêm giờ vào {0} cho nhân viên {1}?
        ///Vui lòng xem kỹ ngày nếu là ca qua đêm của ngày hôm trước..
        /// </summary>
        public static string Text_xacNhanThemGioVaoDonGian {
            get {
                return ResourceManager.GetString("Text_xacNhanThemGioVaoDonGian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn thêm các khai báo vắng cho nhân viên?.
        /// </summary>
        public static string Text_XacNhanThemKhaiVang {
            get {
                return ResourceManager.GetString("Text_XacNhanThemKhaiVang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn xoá giờ {0} của nhân viên?
        ///Vui lòng xem kỹ ngày và thời gian trước khi xoá để không làm sai lệch thời gian tính công của Nhân viên..
        /// </summary>
        public static string Text_xacNhanXoaGioDonGian {
            get {
                return ResourceManager.GetString("Text_xacNhanXoaGioDonGian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn vui lòng xem kỹ giờ trước khi xoá giờ {0} để không làm sai lệch giờ chấm công của nhân viên.
        ///Tiếp tục xoá giờ {0} hàng loạt cho các nhân viên?.
        /// </summary>
        public static string Text_xacNhanXoaGioHangLoat {
            get {
                return ResourceManager.GetString("Text_xacNhanXoaGioHangLoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn xoá các khai báo vắng đang chọn?.
        /// </summary>
        public static string Text_XacNhanXoaKhaiBaoVang {
            get {
                return ResourceManager.GetString("Text_XacNhanXoaKhaiBaoVang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá chi tiết lương công nhật của nhân viên?.
        /// </summary>
        public static string Text_XacNhanXoaLuongCongNhat {
            get {
                return ResourceManager.GetString("Text_XacNhanXoaLuongCongNhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xảy ra lỗi trong quá trình xuất. Vui lòng liên hệ bộ phận kỹ thuật để được trợ giúp..
        /// </summary>
        public static string Text_XayRaLoiTrongQuaTrinhXuatBB {
            get {
                return ResourceManager.GetString("Text_XayRaLoiTrongQuaTrinhXuatBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn xác nhận các ngày làm việc vừa chọn tính phụ cấp tăng cường 50% nếu làm làm việc trên 8 tiếng?.
        /// </summary>
        public static string Text_XNPCTC50 {
            get {
                return ResourceManager.GetString("Text_XNPCTC50", resourceCulture);
            }
        }
    }
}
