//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTQLTTKH {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class ManagerName : global::System.Configuration.ApplicationSettingsBase {
        
        private static ManagerName defaultInstance = ((ManagerName)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ManagerName())));
        
        public static ManagerName Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Lê Anh Tuấn")]
        public string GiamDoc {
            get {
                return ((string)(this["GiamDoc"]));
            }
            set {
                this["GiamDoc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nguyễn Chí Tân")]
        public string PhoGiamDoc {
            get {
                return ((string)(this["PhoGiamDoc"]));
            }
            set {
                this["PhoGiamDoc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nguyễn Quốc Thái")]
        public string KeToanTruong {
            get {
                return ((string)(this["KeToanTruong"]));
            }
            set {
                this["KeToanTruong"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NguoiLapBieuKetCong {
            get {
                return ((string)(this["NguoiLapBieuKetCong"]));
            }
            set {
                this["NguoiLapBieuKetCong"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NguoiLapBieuKetLuong {
            get {
                return ((string)(this["NguoiLapBieuKetLuong"]));
            }
            set {
                this["NguoiLapBieuKetLuong"] = value;
            }
        }
    }
}
