//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChamCong_v03.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChamCong_v03.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LÊ ANH TUẤN.
        /// </summary>
        internal static string anhtuan {
            get {
                return ResourceManager.GetString("anhtuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        internal static string capThongBao {
            get {
                return ResourceManager.GetString("capThongBao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận.
        /// </summary>
        internal static string capXacNhan {
            get {
                return ResourceManager.GetString("capXacNhan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CNS {
            get {
                object obj = ResourceManager.GetObject("CNS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIÁM ĐỐC.
        /// </summary>
        internal static string giamdoc {
            get {
                return ResourceManager.GetString("giamdoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giờ chấm công này đã được xác nhận, không thể thay đổi..
        /// </summary>
        internal static string GioDaXacnhanKhongTheThayDoi {
            get {
                return ResourceManager.GetString("GioDaXacnhanKhongTheThayDoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon_desktop {
            get {
                object obj = ResourceManager.GetObject("icon_desktop", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KẾ TOÁN TRƯỞNG.
        /// </summary>
        internal static string KTT {
            get {
                return ResourceManager.GetString("KTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LẬP BIỂU.
        /// </summary>
        internal static string lapbieu {
            get {
                return ResourceManager.GetString("lapbieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGUYỄN QUỐC THÁI.
        /// </summary>
        internal static string quocthai {
            get {
                return ResourceManager.GetString("quocthai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRƯỞNG BỘ PHẬN.
        /// </summary>
        internal static string truongbp {
            get {
                return ResourceManager.GetString("truongbp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn chuyển đổi giờ {0} {1} thành giờ {2} cho nhân viên {3}?.
        /// </summary>
        internal static string xacNhanChuyenDoiGioDonGian {
            get {
                return ResourceManager.GetString("xacNhanChuyenDoiGioDonGian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn vui lòng xem kỹ lại giờ {0} trước khi sửa giờ để không làm sai lệch giờ chấm công của nhân viên.
        ///Tiếp tục sửa giờ {0} {1} hàng loạt cho các nhân viên?.
        /// </summary>
        internal static string xacNhanSuaGioHangLoat {
            get {
                return ResourceManager.GetString("xacNhanSuaGioHangLoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn sửa giờ ra {0} cho nhân viên {1}?
        ///Vui lòng xem kỹ ngày nếu là giờ qua đêm của ngày hôm sau..
        /// </summary>
        internal static string xacNhanSuaGioRaaDonGian {
            get {
                return ResourceManager.GetString("xacNhanSuaGioRaaDonGian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn sửa giờ vào {0} cho nhân viên {1}?
        ///Vui lòng xem kỹ ngày nếu là giờ qua đêm của ngày hôm trước..
        /// </summary>
        internal static string xacNhanSuaGioVaoDonGian {
            get {
                return ResourceManager.GetString("xacNhanSuaGioVaoDonGian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn vui lòng xem kỹ lại thời gian nhân viên thiếu giờ vào, giờ ra trước khi thêm giờ để không làm sai lệch giờ chấm công của nhân viên.
        ///Tiếp tục thêm giờ {0} {1} hàng loạt cho các nhân viên?.
        /// </summary>
        internal static string xacNhanThemGioHangLoat {
            get {
                return ResourceManager.GetString("xacNhanThemGioHangLoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn thêm giờ ra {0} cho nhân viên {1}?
        ///Vui lòng xem kỹ ngày nếu là ca qua đêm của ngày hôm sau..
        /// </summary>
        internal static string xacNhanThemGioRaaDonGian {
            get {
                return ResourceManager.GetString("xacNhanThemGioRaaDonGian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn thêm giờ vào {0} cho nhân viên {1}?
        ///Vui lòng xem kỹ ngày nếu là ca qua đêm của ngày hôm trước..
        /// </summary>
        internal static string xacNhanThemGioVaoDonGian {
            get {
                return ResourceManager.GetString("xacNhanThemGioVaoDonGian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn muốn xoá giờ {0} của nhân viên?
        ///Vui lòng xem kỹ ngày và thời gian trước khi xoá để không làm sai lệch thời gian tính công của Nhân viên..
        /// </summary>
        internal static string xacNhanXoaGioDonGian {
            get {
                return ResourceManager.GetString("xacNhanXoaGioDonGian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn vui lòng xem kỹ giờ trước khi xoá giờ {0} để không làm sai lệch giờ chấm công của nhân viên.
        ///Tiếp tục xoá giờ {0} hàng loạt cho các nhân viên?.
        /// </summary>
        internal static string xacNhanXoaGioHangLoat {
            get {
                return ResourceManager.GetString("xacNhanXoaGioHangLoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NGUYỄN ĐĂNG XUÂN TÚ.
        /// </summary>
        internal static string xuantu {
            get {
                return ResourceManager.GetString("xuantu", resourceCulture);
            }
        }
    }
}
