using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using ChamCong_v05.DTO;

namespace StudynTestNewTech {
	public partial class test_cell_merging_datagrid : Form {
		public test_cell_merging_datagrid() {
			InitializeComponent();
			// This line of code is generated by Data Source Configuration Wizard
			nhatKyThaoTacTableAdapter1.Fill(wiseEyeV5ExpressDataSet1.NhatKyThaoTac);
			// This line of code is generated by Data Source Configuration Wizard
			nhatKyThaoTacTableAdapter2.Fill(wiseEyeV5ExpressDataSet2.NhatKyThaoTac);
		}

		private void test_cell_merging_datagrid_Load(object sender, EventArgs e) {
			// TODO: This line of code loads data into the 'wiseEyeV5ExpressDataSet.NhatKyThaoTac' table. You can move, or remove it, as needed.
			this.nhatKyThaoTacTableAdapter.Fill(this.wiseEyeV5ExpressDataSet.NhatKyThaoTac);
			DataTable table = new DataTable();
			cCheckInOut a = new cCheckInOut();
			//gridControl1.DataSource 
		}
	}
}
