//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChamCong_v04.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Setting.txt")]
        public string ConnectionStringPath {
            get {
                return ((string)(this["ConnectionStringPath"]));
            }
            set {
                this["ConnectionStringPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastAccLogIn {
            get {
                return ((string)(this["LastAccLogIn"]));
            }
            set {
                this["LastAccLogIn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastServerName {
            get {
                return ((string)(this["LastServerName"]));
            }
            set {
                this["LastServerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastUsername {
            get {
                return ((string)(this["LastUsername"]));
            }
            set {
                this["LastUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastDatabase {
            get {
                return ((string)(this["LastDatabase"]));
            }
            set {
                this["LastDatabase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime LastEndDate {
            get {
                return ((global::System.DateTime)(this["LastEndDate"]));
            }
            set {
                this["LastEndDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime LastStartDate {
            get {
                return ((global::System.DateTime)(this["LastStartDate"]));
            }
            set {
                this["LastStartDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000000")]
        public int LastSanLuong {
            get {
                return ((int)(this["LastSanLuong"]));
            }
            set {
                this["LastSanLuong"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("220")]
        public int LastDonGia {
            get {
                return ((int)(this["LastDonGia"]));
            }
            set {
                this["LastDonGia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1150000")]
        public double LastLuongToiThieu {
            get {
                return ((double)(this["LastLuongToiThieu"]));
            }
            set {
                this["LastLuongToiThieu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1500")]
        public int LastBoiDuongCa3 {
            get {
                return ((int)(this["LastBoiDuongCa3"]));
            }
            set {
                this["LastBoiDuongCa3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int LastTrichQuyLuong {
            get {
                return ((int)(this["LastTrichQuyLuong"]));
            }
            set {
                this["LastTrichQuyLuong"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("730000")]
        public double LastDinhMucComTrua {
            get {
                return ((double)(this["LastDinhMucComTrua"]));
            }
            set {
                this["LastDinhMucComTrua"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30000")]
        public int LastSanluongGiaCongNoibo {
            get {
                return ((int)(this["LastSanluongGiaCongNoibo"]));
            }
            set {
                this["LastSanluongGiaCongNoibo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100000")]
        public int LastSanluongGiacongNgoai {
            get {
                return ((int)(this["LastSanluongGiacongNgoai"]));
            }
            set {
                this["LastSanluongGiacongNgoai"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1600")]
        public int LastDongiaGiacongNoibo {
            get {
                return ((int)(this["LastDongiaGiacongNoibo"]));
            }
            set {
                this["LastDongiaGiacongNoibo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1600")]
        public int LastDongiaGiacongNgoai {
            get {
                return ((int)(this["LastDongiaGiacongNgoai"]));
            }
            set {
                this["LastDongiaGiacongNgoai"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TỔNG CÔNG TY CÔNG NGHIỆP SÀI GÒN")]
        public string headerTCty {
            get {
                return ((string)(this["headerTCty"]));
            }
            set {
                this["headerTCty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TRÁCH NHIỆM HỮU HẠN MỘT THÀNH VIÊN")]
        public string headerTNHH {
            get {
                return ((string)(this["headerTNHH"]));
            }
            set {
                this["headerTNHH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NHÀ MÁY THUỐC LÁ KHÁNH HỘI")]
        public string headerNMTLKH {
            get {
                return ((string)(this["headerNMTLKH"]));
            }
            set {
                this["headerNMTLKH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM")]
        public string headerCHXHCNVN {
            get {
                return ((string)(this["headerCHXHCNVN"]));
            }
            set {
                this["headerCHXHCNVN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Độc lập - Tự do - Hạnh phúc")]
        public string headerDL_TD_HP {
            get {
                return ((string)(this["headerDL_TD_HP"]));
            }
            set {
                this["headerDL_TD_HP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Email: khanhhoi@khcig.com    Website: http://khcig.com")]
        public string headerMailWEB {
            get {
                return ((string)(this["headerMailWEB"]));
            }
            set {
                this["headerMailWEB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Thành phố Hồ Chí Minh, ngày {0} tháng {1} năm {2}")]
        public string headerTPHCMNgaythangnam {
            get {
                return ((string)(this["headerTPHCMNgaythangnam"]));
            }
            set {
                this["headerTPHCMNgaythangnam"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BẢNG CHẤM CÔNG THÁNG {0}")]
        public string titleBangCC_THANG {
            get {
                return ((string)(this["titleBangCC_THANG"]));
            }
            set {
                this["titleBangCC_THANG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BẢNG LƯƠNG THÁNG {0}")]
        public string titleBangLuongThang {
            get {
                return ((string)(this["titleBangLuongThang"]));
            }
            set {
                this["titleBangLuongThang"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BẢNG THANH TOÁN LƯƠNG \r\nCÔNG NHÂN CÔNG NHẬT, THỜI VỤ (chuyển khoản) THÁNG {0}")]
        public string titleBangLuongCongNhat {
            get {
                return ((string)(this["titleBangLuongCongNhat"]));
            }
            set {
                this["titleBangLuongCongNhat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BẢNG TỔNG HỢP CÁC NGUỒN CHI TỪ QUỸ LƯƠNG THÁNG {0}")]
        public string titleBangTongHopChiThang {
            get {
                return ((string)(this["titleBangTongHopChiThang"]));
            }
            set {
                this["titleBangTongHopChiThang"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastTenNVLapBieuLuong {
            get {
                return ((string)(this["LastTenNVLapBieuLuong"]));
            }
            set {
                this["LastTenNVLapBieuLuong"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nguyễn Văn Bé Hai")]
        public string LastTenPhoGD {
            get {
                return ((string)(this["LastTenPhoGD"]));
            }
            set {
                this["LastTenPhoGD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastTenTruongBP {
            get {
                return ((string)(this["LastTenTruongBP"]));
            }
            set {
                this["LastTenTruongBP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Huỳnh Phương")]
        public string LastTenGD {
            get {
                return ((string)(this["LastTenGD"]));
            }
            set {
                this["LastTenGD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nguyễn Quốc Thái")]
        public string LastTenKTT {
            get {
                return ((string)(this["LastTenKTT"]));
            }
            set {
                this["LastTenKTT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastTenNVLapBieuChamCong {
            get {
                return ((string)(this["LastTenNVLapBieuChamCong"]));
            }
            set {
                this["LastTenNVLapBieuChamCong"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("###,###,###,###,###,##0.000;-###,###,###,###,###,##0.000;-?;")]
        public string numFormatMoney30 {
            get {
                return ((string)(this["numFormatMoney30"]));
            }
            set {
                this["numFormatMoney30"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("###,###,##0.00;-###,###,##0.00;-?;")]
        public string numFormatFloat20 {
            get {
                return ((string)(this["numFormatFloat20"]));
            }
            set {
                this["numFormatFloat20"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("###,###,##0.000;-###,###,##0.000;-?;")]
        public string numFormatFloat30 {
            get {
                return ((string)(this["numFormatFloat30"]));
            }
            set {
                this["numFormatFloat30"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("###,###,##0.0;-###,###,##0.0;-?;")]
        public string numFormatFloat10 {
            get {
                return ((string)(this["numFormatFloat10"]));
            }
            set {
                this["numFormatFloat10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("###,###,##0.0#;-###,###,##0.0#;-?;")]
        public string numFormatFloat101F {
            get {
                return ((string)(this["numFormatFloat101F"]));
            }
            set {
                this["numFormatFloat101F"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("###,###,###,###,###,##0;-###,###,###,###,###,##0;-?;")]
        public string numFormatMoney {
            get {
                return ((string)(this["numFormatMoney"]));
            }
            set {
                this["numFormatMoney"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("###,###,###,###,##0;-###,###,###,###,##0;-?;")]
        public string numFormatInt {
            get {
                return ((string)(this["numFormatInt"]));
            }
            set {
                this["numFormatInt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01/06/2014 13:00:00")]
        public global::System.DateTime testDateTimeDiemDanh {
            get {
                return ((global::System.DateTime)(this["testDateTimeDiemDanh"]));
            }
            set {
                this["testDateTimeDiemDanh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TemplateChiTietLuong.xlsx")]
        public string pathReportChiTietLuong {
            get {
                return ((string)(this["pathReportChiTietLuong"]));
            }
            set {
                this["pathReportChiTietLuong"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TemplateTamUng_MucDongBHXH.xlsx")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ca8g")]
        public string shiftCodeCa8h {
            get {
                return ((string)(this["shiftCodeCa8h"]));
            }
            set {
                this["shiftCodeCa8h"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ca12g")]
        public string shiftCodeCa12h {
            get {
                return ((string)(this["shiftCodeCa12h"]));
            }
            set {
                this["shiftCodeCa12h"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ca4g")]
        public string shiftCodeCa4h {
            get {
                return ((string)(this["shiftCodeCa4h"]));
            }
            set {
                this["shiftCodeCa4h"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ca16g")]
        public string shiftCodeCa16h {
            get {
                return ((string)(this["shiftCodeCa16h"]));
            }
            set {
                this["shiftCodeCa16h"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CaTựDo")]
        public string shiftCodeCaTD8h {
            get {
                return ((string)(this["shiftCodeCaTD8h"]));
            }
            set {
                this["shiftCodeCaTD8h"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public string kyHieuCCCa4h {
            get {
                return ((string)(this["kyHieuCCCa4h"]));
            }
            set {
                this["kyHieuCCCa4h"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public string kyHieuCCCa8h {
            get {
                return ((string)(this["kyHieuCCCa8h"]));
            }
            set {
                this["kyHieuCCCa8h"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D")]
        public string kyHieuCCCa12h {
            get {
                return ((string)(this["kyHieuCCCa12h"]));
            }
            set {
                this["kyHieuCCCa12h"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16g")]
        public string kyHieuCCCa16h {
            get {
                return ((string)(this["kyHieuCCCa16h"]));
            }
            set {
                this["kyHieuCCCa16h"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TD")]
        public string kyHieuCCCaTD {
            get {
                return ((string)(this["kyHieuCCCaTD"]));
            }
            set {
                this["kyHieuCCCaTD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tính công theo giờ làm (mức trần {0} giờ) bắt đầu từ lúc check vào ")]
        public string MoTaCaTuDo {
            get {
                return ((string)(this["MoTaCaTuDo"]));
            }
            set {
                this["MoTaCaTuDo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public int sizeHeaderBKC_TCTCNSG {
            get {
                return ((int)(this["sizeHeaderBKC_TCTCNSG"]));
            }
            set {
                this["sizeHeaderBKC_TCTCNSG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22")]
        public int sizeTitleBKC {
            get {
                return ((int)(this["sizeTitleBKC"]));
            }
            set {
                this["sizeTitleBKC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int viTriOHeaderBKC_TCTCNSG {
            get {
                return ((int)(this["viTriOHeaderBKC_TCTCNSG"]));
            }
            set {
                this["viTriOHeaderBKC_TCTCNSG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("34")]
        public int viTriOHeaderBKC_DiaChi {
            get {
                return ((int)(this["viTriOHeaderBKC_DiaChi"]));
            }
            set {
                this["viTriOHeaderBKC_DiaChi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public int viTriOHeaderTitle {
            get {
                return ((int)(this["viTriOHeaderTitle"]));
            }
            set {
                this["viTriOHeaderTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int cachDongBKC_LapBieu_ten {
            get {
                return ((int)(this["cachDongBKC_LapBieu_ten"]));
            }
            set {
                this["cachDongBKC_LapBieu_ten"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime LastThangKetCong {
            get {
                return ((global::System.DateTime)(this["LastThangKetCong"]));
            }
            set {
                this["LastThangKetCong"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("(CNS)")]
        public string headerCNS {
            get {
                return ((string)(this["headerCNS"]));
            }
            set {
                this["headerCNS"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2135000")]
        public int MucLuongTT172135 {
            get {
                return ((int)(this["MucLuongTT172135"]));
            }
        }
    }
}
